namespace OutreachGenie.Domain.Enums;

/// <summary>
/// Indicates the origin of an artifact for audit and trust purposes.
/// </summary>
public enum ArtifactSource
{
    /// <summary>
    /// Artifact explicitly provided or approved by user.
    /// </summary>
    User,

    /// <summary>
    /// Artifact generated by agent during execution.
    /// </summary>
    Agent,

    /// <summary>
    /// Artifact created by system (migrations, defaults).
    /// </summary>
    System,
}
